import type { CandidatePost } from "../shared/types.js";

/**
 * Synthetic candidates stand in for Earlybird search results and UTEG responses,
 * which depend on private X infrastructure and user data not included in the
 * open-source repository.
 */
export const CANDIDATES: readonly CandidatePost[] = [
  {
    id: "post-evals-over-vibes",
    author: {
      id: "mira-chen",
      name: "Mira Chen",
      handle: "@mirabuilds",
      title: "Applied AI researcher",
      initials: "MC",
      gradient: "linear-gradient(135deg, #6f52c7, #ba8af2)",
      verified: true,
    },
    text: "The best AI teams I know replaced “this feels better” with tiny, task-specific evals. Ten examples that mirror real work will teach you more than a giant benchmark no one on your team understands.",
    topic: "ai",
    publishedAt: "2026-08-03T14:48:00.000Z",
    earlybirdScore: 0.92,
    baseRealGraphScore: 0.38,
    metrics: { replies: 84, reposts: 642, likes: 4800, views: 182000 },
    visual: {
      eyebrow: "Field note · AI evaluation",
      value: "10 > 10k",
      caption: "Representative examples beat impressive-looking benchmarks.",
      gradient: "linear-gradient(135deg, #2b174f 0%, #6f52c7 55%, #d2b5ff 100%)",
    },
  },
  {
    id: "post-latency-budget",
    author: {
      id: "jon-bell",
      name: "Jon Bell",
      handle: "@joncodes",
      title: "Infrastructure engineer",
      initials: "JB",
      gradient: "linear-gradient(135deg, #164e73, #58a7d4)",
      verified: true,
    },
    text: "A useful latency budget is a product decision, not an infrastructure number. Start with the moment a person notices, then spend milliseconds where they create the most confidence.",
    topic: "engineering",
    publishedAt: "2026-08-03T13:32:00.000Z",
    earlybirdScore: 0.79,
    baseRealGraphScore: 0.52,
    hasReply: true,
    metrics: { replies: 41, reposts: 233, likes: 2100, views: 76000 },
  },
  {
    id: "post-progressive-disclosure",
    author: {
      id: "ana-sol",
      name: "Ana Sol",
      handle: "@anasol",
      title: "Product designer",
      initials: "AS",
      gradient: "linear-gradient(135deg, #9b3657, #e794a9)",
    },
    text: "Progressive disclosure isn’t hiding complexity. It’s sequencing it. Show people the one decision they can make now, then reveal the next decision their answer unlocks.",
    topic: "design",
    publishedAt: "2026-08-03T12:10:00.000Z",
    earlybirdScore: 0.84,
    baseRealGraphScore: 0.34,
    metrics: { replies: 29, reposts: 188, likes: 1700, views: 59000 },
    visual: {
      eyebrow: "Interaction principle",
      value: "One clear next step",
      caption: "Complexity becomes manageable when decisions arrive in order.",
      gradient: "linear-gradient(135deg, #591f38 0%, #ba4f70 58%, #f2b7c5 100%)",
    },
  },
  {
    id: "post-cities-cooler",
    author: {
      id: "leila-okafor",
      name: "Leila Okafor",
      handle: "@leilaearth",
      title: "Urban climate scientist",
      initials: "LO",
      gradient: "linear-gradient(135deg, #356824, #8ebb60)",
      verified: true,
    },
    text: "Cooling a city is a portfolio problem: shade for walking routes, reflective surfaces for roofs, and trees where their canopies can survive. The strongest plans measure comfort at street level.",
    topic: "climate",
    publishedAt: "2026-08-03T11:42:00.000Z",
    earlybirdScore: 0.72,
    baseRealGraphScore: 0.29,
    metrics: { replies: 56, reposts: 391, likes: 3100, views: 128000 },
  },
  {
    id: "post-small-model-routing",
    author: {
      id: "dev-patel",
      name: "Dev Patel",
      handle: "@devonmodels",
      title: "ML systems lead",
      initials: "DP",
      gradient: "linear-gradient(135deg, #4b3989, #8f78dc)",
    },
    text: "Model routing is becoming the quiet superpower of AI products. Let a small model classify intent and uncertainty; spend the expensive call only when the task earns it.",
    topic: "ai",
    publishedAt: "2026-08-03T10:55:00.000Z",
    earlybirdScore: 0.76,
    baseRealGraphScore: 0.46,
    hasReply: true,
    metrics: { replies: 63, reposts: 402, likes: 3600, views: 141000 },
    visual: {
      eyebrow: "System pattern",
      value: "Route, then reason",
      caption: "Match model cost to task complexity.",
      gradient: "linear-gradient(135deg, #1f183c 0%, #5945a0 58%, #a997eb 100%)",
    },
  },
  {
    id: "post-invisible-interface",
    author: {
      id: "theo-martin",
      name: "Théo Martin",
      handle: "@theomakes",
      title: "Design engineer",
      initials: "TM",
      gradient: "linear-gradient(135deg, #a44e35, #e5a46e)",
      verified: true,
    },
    text: "The most satisfying interface detail is often the one that prevents a question: a saved state that looks saved, a button that explains why it’s disabled, a draft that never disappears.",
    topic: "design",
    publishedAt: "2026-08-03T09:38:00.000Z",
    earlybirdScore: 0.81,
    baseRealGraphScore: 0.31,
    metrics: { replies: 24, reposts: 146, likes: 1900, views: 62000 },
  },
  {
    id: "post-ocean-sound",
    author: {
      id: "noor-rahman",
      name: "Noor Rahman",
      handle: "@noorobserves",
      title: "Marine biologist",
      initials: "NR",
      gradient: "linear-gradient(135deg, #11636e, #54b8b1)",
      verified: true,
    },
    text: "An ocean recording can be a biodiversity survey. Fish, shrimp, boats, and rainfall each leave acoustic fingerprints; long-running microphones let researchers hear a reef change before they can see it.",
    topic: "science",
    publishedAt: "2026-08-03T08:20:00.000Z",
    earlybirdScore: 0.68,
    baseRealGraphScore: 0.41,
    metrics: { replies: 37, reposts: 290, likes: 2800, views: 107000 },
    visual: {
      eyebrow: "Listen to the ecosystem",
      value: "24 hr",
      caption: "Passive acoustics captures the rhythms a daytime survey misses.",
      gradient: "linear-gradient(135deg, #073d4d 0%, #168292 55%, #78d5c9 100%)",
    },
  },
  {
    id: "post-boring-migrations",
    author: {
      id: "imani-brooks",
      name: "Imani Brooks",
      handle: "@imanib",
      title: "Staff software engineer",
      initials: "IB",
      gradient: "linear-gradient(135deg, #255a8f, #6ba6d9)",
    },
    text: "Make database migrations boring: expand before you contract, dual-read only when you can observe disagreements, and make every step safe to pause. Clever migrations are expensive stories later.",
    topic: "engineering",
    publishedAt: "2026-08-02T22:51:00.000Z",
    earlybirdScore: 0.74,
    baseRealGraphScore: 0.48,
    hasReply: true,
    metrics: { replies: 71, reposts: 510, likes: 4300, views: 166000 },
  },
  {
    id: "post-questions-in-museums",
    author: {
      id: "elena-rossi",
      name: "Elena Rossi",
      handle: "@elenasees",
      title: "Museum educator",
      initials: "ER",
      gradient: "linear-gradient(135deg, #8a5527, #d8a35e)",
    },
    text: "A good museum label gives you one fact. A great one gives you a question you keep carrying to the next room.",
    topic: "culture",
    publishedAt: "2026-08-02T20:16:00.000Z",
    earlybirdScore: 0.63,
    baseRealGraphScore: 0.18,
    metrics: { replies: 18, reposts: 121, likes: 1500, views: 48000 },
  },
  {
    id: "post-uncertainty-language",
    author: {
      id: "samira-adebayo",
      name: "Samira Adebayo",
      handle: "@samira_data",
      title: "Data journalist",
      initials: "SA",
      gradient: "linear-gradient(135deg, #295e55, #72ad8d)",
      verified: true,
    },
    text: "Uncertainty is information, not an apology. “The range is likely 20–30” helps someone decide. “We can’t know exactly” leaves them with nothing to use.",
    topic: "science",
    publishedAt: "2026-08-02T18:04:00.000Z",
    earlybirdScore: 0.77,
    baseRealGraphScore: 0.27,
    metrics: { replies: 46, reposts: 356, likes: 3300, views: 119000 },
  },
  {
    id: "post-agents-boundaries",
    author: {
      id: "alex-kim",
      name: "Alex Kim",
      handle: "@alexcoordinates",
      title: "AI product engineer",
      initials: "AK",
      gradient: "linear-gradient(135deg, #53379a, #a786e2)",
    },
    text: "Reliable agents need explicit boundaries more than bigger prompts: what can be changed, what must be confirmed, how success is checked, and where to stop.",
    topic: "ai",
    publishedAt: "2026-08-02T16:27:00.000Z",
    earlybirdScore: 0.88,
    baseRealGraphScore: 0.36,
    hasReply: true,
    metrics: { replies: 95, reposts: 701, likes: 5200, views: 204000 },
  },
  {
    id: "post-repair-culture",
    author: {
      id: "mina-jensen",
      name: "Mina Jensen",
      handle: "@minamends",
      title: "Independent maker",
      initials: "MJ",
      gradient: "linear-gradient(135deg, #9a5c2f, #e0a96f)",
    },
    text: "Repair cafés work because expertise becomes social. Someone arrives with a broken lamp and leaves knowing how a switch works—and knowing a neighbor who can help next time.",
    topic: "culture",
    publishedAt: "2026-08-02T13:09:00.000Z",
    earlybirdScore: 0.59,
    baseRealGraphScore: 0.23,
    metrics: { replies: 22, reposts: 164, likes: 2100, views: 71000 },
    visual: {
      eyebrow: "Community pattern",
      value: "Fix it together",
      caption: "Shared skills make everyday objects—and neighborhoods—last longer.",
      gradient: "linear-gradient(135deg, #4b2b1b 0%, #a56738 58%, #eec28d 100%)",
    },
  },
  {
    id: "post-energy-feedback",
    author: {
      id: "owen-price",
      name: "Owen Price",
      handle: "@owenenergy",
      title: "Energy systems analyst",
      initials: "OP",
      gradient: "linear-gradient(135deg, #477326, #9ab85b)",
    },
    text: "Energy feedback works when it connects an action to an outcome quickly. A monthly bill is accounting; a same-day signal can become a habit.",
    topic: "climate",
    publishedAt: "2026-08-02T10:44:00.000Z",
    earlybirdScore: 0.65,
    baseRealGraphScore: 0.33,
    hasReply: true,
    metrics: { replies: 31, reposts: 210, likes: 1800, views: 68000 },
  },
  {
    id: "post-observability-question",
    author: {
      id: "ruth-okoye",
      name: "Ruth Okoye",
      handle: "@ruthships",
      title: "Reliability engineer",
      initials: "RO",
      gradient: "linear-gradient(135deg, #275d84, #7db2d4)",
      verified: true,
    },
    text: "Before adding a dashboard, write the question it should answer during an incident. If the sentence has three “ands,” you probably need three smaller views.",
    topic: "engineering",
    publishedAt: "2026-08-01T21:13:00.000Z",
    earlybirdScore: 0.7,
    baseRealGraphScore: 0.43,
    metrics: { replies: 52, reposts: 333, likes: 2900, views: 111000 },
  },
  {
    id: "post-random-walk",
    author: {
      id: "luca-wren",
      name: "Luca Wren",
      handle: "@lucawanders",
      title: "Sound artist",
      initials: "LW",
      gradient: "linear-gradient(135deg, #b05c35, #e9b363)",
    },
    text: "Try this on your next walk: follow the quietest sound you can hear for five minutes. Cities have layers that only appear when you stop choosing the destination.",
    topic: "culture",
    publishedAt: "2026-08-01T17:37:00.000Z",
    earlybirdScore: 0.21,
    baseRealGraphScore: 0.08,
    isRandomTweet: true,
    metrics: { replies: 12, reposts: 76, likes: 980, views: 32000 },
    visual: {
      eyebrow: "A small invitation",
      value: "Follow the quiet",
      caption: "This is an exploration pick, set aside before ranking.",
      gradient: "linear-gradient(135deg, #563420 0%, #b46b3e 55%, #f0c477 100%)",
    },
  },
];
